### ISSUE TITLE
Primary Image Covers not showing for Recorded TV

### ISSUE THREAD

**Issue by hooray4me** [MediaBrowser/Emby.Releases#27]
After the update to 4.1.1.0 primary image covers are not showing for recorded TV in "Latest Recordings"

![image](https://user-images.githubusercontent.com/12399138/57045297-c291a400-6c32-11e9-9f79-1cb139ba4beb.png)

If I click into the episode, I can see an image.
![image](https://user-images.githubusercontent.com/12399138/57045328-ddfcaf00-6c32-11e9-9bcd-0fca28f02397.png)

Here are the logs:
`2019-05-01 16:56:19.186 Info HttpServer: HTTP Response 200 to 10.40.2.56. Time: 63ms. https://tv.xxxxxxx.com:8920/emby/Users/70ed5f4b409f4dcd83526a04bc25e0a8/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=767bffe4f11c93ef34b805451a696a4e
2019-05-01 16:56:19.194 Info HttpServer: HTTP GET https://tv.xxxxxxx.com:8920/emby/Items/9d7ad6afe9afa2dab1a2f6e00ad28fa6/Images/Primary?maxHeight=118&maxWidth=209&tag=8ca400e22f96451b4b2dd430b709f55f&quality=90. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
2019-05-01 16:56:19.200 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.1.0.26
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby-server -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.45
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Program data path: /var/lib/emby-server
	Application directory: /opt/emby-server/system
	System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
	   at Emby.Server.Implementations.IO.SharpCifsFileSystem.IsEnabledForPath(String path)
	   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileStream(String path, FileOpenMode mode, FileAccessMode access, FileShareMode share, Boolean isAsync)
	   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.GetLazyImage(String key, BaseItem item, ImageType type, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Boolean IsEnabledForPath(System.String)
	
2019-05-01 16:56:19.201 Info HttpServer: HTTP Response 500 to 10.40.2.56. Time: 6ms. https://tv.xxxxxxx.com:8920/emby/Items/9d7ad6afe9afa2dab1a2f6e00ad28fa6/Images/Primary?maxHeight=118&maxWidth=209&tag=8ca400e22f96451b4b2dd430b709f55f&quality=90
2019-05-01 16:56:19.203 Info HttpServer: HTTP Response 200 to 10.40.2.56. Time: 68ms. https://tv.xxxxxxx.com:8920/emby/Users/70ed5f4b409f4dcd83526a04bc25e0a8/Items/Latest?Limit=30&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=7e64e319657a9516ec78490da03edccb
2019-05-01 16:56:19.212 Info HttpServer: HTTP Response 200 to 10.40.2.56. Time: 85ms. https://tv.xxxxxxx.com:8920/emby/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CSeriesInfo%2CDateCreated%2CBasicSyncInfo&UserId=70ed5f4b409f4dcd83526a04bc25e0a8&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false
2019-05-01 16:56:19.317 Info HttpServer: HTTP GET https://tv.xxxxxxx.com:8920/emby/Items/34855/Images/Thumb?maxWidth=271&tag=d6ad8fc9052a8dfb5ded3cd6b702d052&quality=90. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
2019-05-01 16:56:19.318 Info HttpServer: HTTP GET https://tv.xxxxxxx.com:8920/emby/Items/34838/Images/Thumb?maxWidth=271&tag=7a22f2c80e610125624f8e82071e2b70&quality=90. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
2019-05-01 16:56:19.318 Info HttpClient: GET https://assets.fanart.tv/fanart/tv/77075/tvthumb/jeopardy-4f5b9a8d8ea98.jpg
2019-05-01 16:56:19.319 Info HttpClient: GET https://assets.fanart.tv/fanart/tv/72194/tvthumb/the-ellen-degeneres-show-50f4a6bb7ebd9.jpg
2019-05-01 16:56:22.066 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0
2019-05-01 16:56:22.068 Info HttpServer: HTTP Response 200 to 10.40.0.145. Time: 2ms. http://tv.xxxxxxx.com:8096/emby/Sessions
2019-05-01 16:56:24.065 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0
2019-05-01 16:56:24.072 Info HttpServer: HTTP Response 200 to 10.40.0.145. Time: 7ms. http://tv.xxxxxxx.com:8096/emby/Sessions
2019-05-01 16:56:24.157 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0
2019-05-01 16:56:24.159 Info HttpServer: HTTP Response 200 to 10.40.0.145. Time: 2ms. http://tv.xxxxxxx.com:8096/emby/Sessions
2019-05-01 16:56:28.061 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0
2019-05-01 16:56:28.063 Info HttpServer: HTTP Response 200 to 10.40.0.145. Time: 2ms. http://tv.xxxxxxx.com:8096/emby/Sessions
2019-05-01 16:56:29.084 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0
2019-05-01 16:56:29.086 Info HttpServer: HTTP Response 200 to 10.40.0.145. Time: 2ms. http://tv.xxxxxxx.com:8096/emby/Sessions
2019-05-01 16:56:29.179 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0
2019-05-01 16:56:29.181 Info HttpServer: HTTP Response 200 to 10.40.0.145. Time: 2ms. http://tv.xxxxxxx.com:8096/emby/Sessions
2019-05-01 16:56:34.084 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0
2019-05-01 16:56:34.086 Info HttpServer: HTTP Response 200 to 10.40.0.145. Time: 2ms. http://tv.xxxxxxx.com:8096/emby/Sessions
2019-05-01 16:56:34.100 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0
2019-05-01 16:56:34.101 Info HttpServer: HTTP Response 200 to 10.40.0.145. Time: 1ms. http://tv.xxxxxxx.com:8096/emby/Sessions
2019-05-01 16:56:34.183 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0
2019-05-01 16:56:34.184 Info HttpServer: HTTP Response 200 to 10.40.0.145. Time: 1ms. http://tv.xxxxxxx.com:8096/emby/Sessions
2019-05-01 16:56:39.067 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0
2019-05-01 16:56:39.073 Info HttpServer: HTTP Response 200 to 10.40.0.145. Time: 6ms. http://tv.xxxxxxx.com:8096/emby/Sessions
2019-05-01 16:56:39.160 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0
2019-05-01 16:56:39.162 Info HttpServer: HTTP Response 200 to 10.40.0.145. Time: 2ms. http://tv.xxxxxxx.com:8096/emby/Sessions
2019-05-01 16:56:39.317 Error HttpClient: Connection to https://assets.fanart.tv/fanart/tv/72194/tvthumb/the-ellen-degeneres-show-50f4a6bb7ebd9.jpg timed out
2019-05-01 16:56:39.319 Error HttpClient: Connection to https://assets.fanart.tv/fanart/tv/77075/tvthumb/jeopardy-4f5b9a8d8ea98.jpg timed out
2019-05-01 16:56:39.328 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.1.0.26
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby-server -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.45
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Program data path: /var/lib/emby-server
	Application directory: /opt/emby-server/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Connection to https://assets.fanart.tv/fanart/tv/72194/tvthumb/the-ellen-degeneres-show-50f4a6bb7ebd9.jpg timed out ---> System.OperationCanceledException: The operation was canceled.
	   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
	   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   --- End of inner exception stack trace ---
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	InnerException: System.OperationCanceledException: The operation was canceled.
	Source: System.Net.Http
	TargetSite: Void HandleFinishSendAsyncError(System.Exception, System.Threading.CancellationTokenSource)
	   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
	   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	
2019-05-01 16:56:39.328 Info HttpServer: HTTP Response 500 to 10.40.2.56. Time: 20010ms. https://tv.xxxxxxx.com:8920/emby/Items/34838/Images/Thumb?maxWidth=271&tag=7a22f2c80e610125624f8e82071e2b70&quality=90
2019-05-01 16:56:39.329 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.1.0.26
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby-server -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.45
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Program data path: /var/lib/emby-server
	Application directory: /opt/emby-server/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Connection to https://assets.fanart.tv/fanart/tv/77075/tvthumb/jeopardy-4f5b9a8d8ea98.jpg timed out ---> System.OperationCanceledException: The operation was canceled.
	   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
	   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   --- End of inner exception stack trace ---
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	InnerException: System.OperationCanceledException: The operation was canceled.
	Source: System.Net.Http
	TargetSite: Void HandleFinishSendAsyncError(System.Exception, System.Threading.CancellationTokenSource)
	   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
	   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	
2019-05-01 16:56:39.329 Info HttpServer: HTTP Response 500 to 10.40.2.56. Time: 20012ms. https://tv.xxxxxxx.com:8920/emby/Items/34855/Images/Thumb?maxWidth=271&tag=d6ad8fc9052a8dfb5ded3cd6b702d052&quality=90
2019-05-01 16:56:40.062 Info HttpServer: HTTP GET http://tv.xxxxxxx.com:8096/emby/Sessions. UserAgent: curl/7.58.0`

**Comment by LukePulverenti** [comment]
Are you still seeing this?

**Comment by hooray4me** [comment]
yes I am

**Comment by LukePulverenti** [comment]
In your log posting above it looks like a connection timed out to fanart.tv. If fanart is still doing this for you, then you can always turn it off for your recordings library.

**Comment by LukePulverenti** [comment]
HI, has this answered your question?

**Comment by LukePulverenti** [comment]
Hi there @hooray4me , has this helped?

**Comment by hooray4me** [comment]
I'm not seeing this issue anymore. Thanks
